description: Runs create-typescript-app in transition mode

name: Transition

runs:
  steps:
    - uses: ./.github/actions/prepare
    - run: npx create-typescript-app
      shell: bash
    - id: auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_author: The Friendly Bingo Bot <bot@create.bingo>
        commit_message: Check in changes from re-running npx create-typescript-app
        commit_user_email: bot@create.bingo
        commit_user_name: The Friendly Bingo Bot
    - if: steps.auto-commit-action.outputs.changes_detected == 'true'
      uses: mshick/add-pr-comment@v2
      with:
        issue: ${{ github.event.pull_request.number }}
        message: |-
          🤖 Beep boop! I ran `npx create-typescript-app` and it updated some files.

          I went ahead and checked those changes into this PR for you. Please review the latest commit to see if you want to merge it.

          Cheers!
           — _The Friendly Bingo Bot_ 💝

          > ℹ️ These automatic commits keep your repository up-to-date with new versions of [create-typescript-app](https://github.com/JoshuaKGoldberg/create-typescript-app). If you want to opt out, delete your `.github/workflows/cta-transitions.yml` file.
  using: composite
