jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm build:docs

name: Build Docs

on:
  pull_request: ~
  push:
    branches:
      - main
