jobs:
  transition:
    name: Transition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.ACCESS_TOKEN }}
      - id: check
        if: (github.actor == 'JoshuaKGoldberg' || github.actor == 'renovate[bot]') && startsWith(github.head_ref, 'renovate/') && contains(github.event.pull_request.title, 'create-typescript-app')
        uses: ./.github/actions/transition
      - if: steps.check.outcome == 'skipped'
        run: echo 'Skipping transition mode because the PR does not appear to be an automated or owner-created update to create-typescript-app.'

name: CTA

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
