jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-node-14-${{ hashFiles('./package*json') }}
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ['build', 'format:check', 'lint', 'test']

name: CI
on: push
